### ISSUE TITLE
How to push content

### ISSUE THREAD

**Issue by ltboye** [STAMP-project/descartes-usecases-output#12]
Could someone explain how I can contribute to the repo? I have cloned it locally, and started putting in Tellu content, but I am not allowed to push (github returns 403).

**Comment by jesus-gorronogoitia** [comment]
hi @ltboye , please give me your Github account to grant you writing access to this repository (if I can, because I am not the repository owner)

**Comment by ltboye** [comment]
@jesus-gorronogoitia user ltboye, email lars.thomas.boye@tellu.no

**Comment by ltboye** [comment]
@jesus-gorronogoitia Great, thanks!
